### ISSUE TITLE
unsorted_bin_attack partially works with glibc 2.27

### ISSUE THREAD

**Issue by mtdcr** [shellphish/how2heap#103]
According to `unsorted_bin_attack.c`, this „only works with disabled tcache-option for glibc“. `README.md` lists it as applicable to < 2.26. But you can use it with 2.27, if your chunks are big enough to not go into tcache. This was used in [Worldwide Highest Velocity](https://2019.squarectf.com/challenge?WZIcIoecgyY) at SquareCTF 2019.

**Comment by Kyle-Kyle** [comment]
Since it is merged, I think this can be closed?

**Comment by mtdcr** [comment]
Yes, thank you!
