### ISSUE TITLE
Update the glibc_ChangeLog.md

### ISSUE THREAD

**Issue by m1ghtym0** [shellphish/how2heap#106]
Add changes for:
Especially the tcache->key thing they added.
- [ ] 2.28
- [ ] 2.29
- [ ] 2.30

**Comment by Kyle-Kyle** [comment]
and bunch of security checks in 2.29. A lot of current techniques fail to work on 2.29.

**Comment by Kyle-Kyle** [comment]
I added a `Patch` section in README. It shows what commit kills which technique.
Is that good enough?

**Comment by m1ghtym0** [comment]
Sure thing! Thanks Kyle!
