### ISSUE TITLE
Update House of Force Version Info

### ISSUE THREAD

**Issue by xavierholt** [shellphish/how2heap#108]
The main page claims that libc < 2.29 is vulnerable to the House of Force attack, but the `malloc(): corrupted top size` check seems to have been backported to previous versions.  My 2.28 libc contains this check.  Prior versions may have received the fix as well.

**Comment by Kyle-Kyle** [comment]
1. libc is always updating. If we keep update with the latest protections, it will be much harder for beginner to start and hard to maintain.
2. Here the libc means the libc shipped in  ubuntu. So libc-2.28 means the libc shipped in ubuntu-18.10

**Comment by xavierholt** [comment]
Makes sense.  My libc was from Debian 10.  It might be nice to specify that those version numbers are specifically for Ubuntu, though, so others don't get confused like I did.
