### ISSUE TITLE
malloc size didn't match with the size in comment

### ISSUE THREAD

**Issue by ucgJhe** [shellphish/how2heap#109]
https://github.com/shellphish/how2heap/blob/dc6fc154166c1d50a9c2e3b4be7665cd80d658bb/first_fit.c#L30

 Does this supposed to be 0x506 here, or I am just getting it wrong ?

**Comment by Kyle-Kyle** [comment]
fixed in dfa1809ec9c4e4219d74a1f991a2b7518e591146
Thanks!
