### ISSUE TITLE
No make rule for libdl.so.2

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [shellphish/how2heap#123]
I'm getting this error when trying to compile glibc 2.25/2.26. I also had to use --disable-werror inside the Makefile, but that's another thing.

`make[2]: *** No rule to make target '/home/kali/pentest/reversing/how2heap/glibc_build/dlfcn/libdl.so.2', needed by '/home/kali/pentest/reversing/how2heap/glibc_build/malloc/libmemusage.so'.  Stop.`

**Comment by Kyle-Kyle** [comment]
we moved away from the `glibc_build` system recently. So I'm closing this.
