### ISSUE TITLE
wrong in unsafe_unlink.c in glibc2.31

### ISSUE THREAD

**Issue by cheaterdxd** [shellphish/how2heap#132]
at line 40,
chunk1_hdr[0] = malloc_size;
	fprintf(stderr, "If we had 'normally' freed chunk0, chunk1.previous_size would have been 0x90, however this is its new value: %p\n",(void*)chunk1_hdr[0]);
i think if normally freed, the chunk1.previous_size must be 0x430 instead 0x90.

**Comment by Kyle-Kyle** [comment]
yeah you are right, it is some leftover from the old version.
fixed in 00f39eba900936e4330295d41a887dbfe0d97bab.
Thanks for reporting!
