### ISSUE TITLE
house_of_lore.c in glibc_2.31 is incorrect

### ISSUE THREAD

**Issue by Demon-Wang** [shellphish/how2heap#140]
hi, the house_of_lore.c in glibc_2.31 is old ,which may be the 2.27 version but need change memcpy's offset(+0x68) i'm not sure this is same in different environment. :)

**Comment by Kyle-Kyle** [comment]
thank you for reminding me the issue. I fixed it by using gcc's `__builtin_frame_address` intrinsic, which should work across versions.

**Comment by Kyle-Kyle** [comment]
the patch is [here](https://github.com/shellphish/how2heap/commit/e8fbd0a6f72be2125ab39c4db2899f01d286a281)

**Comment by Kyle-Kyle** [comment]
I guess it is safe to close the issue now. Please feel free to reopen it if you find any issues in terms of the patch.
