### ISSUE TITLE
tcache_dup.c link in readme points to 404 page

### ISSUE THREAD

**Issue by 0x3c3e** [shellphish/how2heap#146]
That line https://github.com/shellphish/how2heap/blob/master/README.md?plain=1#L30
URL: https://github.com/shellphish/how2heap/blob/master/glibc_2.27/tcache_dup.c

**Comment by Kyle-Kyle** [comment]
thanks for pointing out the error. It is fixed in 760ab55

**Comment by Kyle-Kyle** [comment]
feel free to reopen the issue if you think there is anything wrong with the patch or questions.
