### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by jarun** [shellphish/how2heap#5]
While compiling on Ubuntu 14.044.3, gcc version 4.8.4, I got the following error:
<pre>$ make
cc -std=c99    fastbin_dup.c   -o fastbin_dup
cc -std=c99    fastbin_dup_into_stack.c   -o fastbin_dup_into_stack
cc -std=c99    unsafe_unlink.c   -o unsafe_unlink
cc -std=c99    house_of_spirit.c   -o house_of_spirit
cc -std=c99    poison_null_byte.c   -o poison_null_byte
cc -std=c99    malloc_playground.c   -o malloc_playground
malloc_playground.c: In function ‘main’:
malloc_playground.c:27:3: warning: ‘gets’ is deprecated (declared at /usr/include/stdio.h:638) [-Wdeprecated-declarations]
   gets(buffer);
   ^
/tmp/ccquQQGB.o: In function `main':
malloc_playground.c:(.text+0xc2): warning: the `gets' function is dangerous and should not be used.</pre>

**Comment by zardus** [comment]
That's a warning, not an error, so it should still have built the binary. Was the `malloc_playground` binary created?

**Comment by jarun** [comment]
Sorry, I added a -Werror as well when I compiled it first. Old habit of mine. When I copied here, I copied the warning from the unpatched code.
I can see that you have fixed it in the latest commit. Thanks!
