### ISSUE TITLE
"Applicable CTF Challenges" provide binary file would be more helpful.

### ISSUE THREAD

**Issue by lonnywang** [shellphish/how2heap#50]
Such as "[Insomni'hack 2017-Wheel of Robots](https://gist.github.com/niklasb/074428333b817d2ecb63f7926074427a)", there is a writeup, but no binary file.

**Comment by zardus** [comment]
@niklasb, would you happen to have that bin laying around?

**Comment by niklasb** [comment]
I added the binary to the gist: https://gist.github.com/niklasb/074428333b817d2ecb63f7926074427a/raw/a6e78619f7f3fe678576502b981fbc6f8193549c/wheelofrobots_b417d417b5ad4c3dc8a225ba5ef79994

**Comment by zardus** [comment]
Thanks!
