### ISSUE TITLE
Need the binary file for Insomni'hack 2017-Wheel of Robots

### ISSUE THREAD

**Issue by sivaramaaa** [shellphish/how2heap#54]
It would be great if someone can provide me the file for Insomni'hack 2017-Wheel of Robots
i have looked all over the internet for this file , but no luck . 
I want to practice on topic "Unsafe Unlink"

**Comment by m1ghtym0** [comment]
Are you still looking for this?
Did you try to contact the hxp-guys?
[writeup](https://hxp.io/blog/31/Insomnihack%202017:%20%22wheel%20of%20robots%22%20writeup/)
[contact](https://hxp.io/contact/)

**Comment by sivaramaaa** [comment]
Thanks
I will try to contact them , hope I get the binary :)

**Comment by P4N74** [comment]
there is already a challenge binary on the gist link given in the description. https://gist.github.com/niklasb/074428333b817d2ecb63f7926074427a#file-wheelofrobots_b417d417b5ad4c3dc8a225ba5ef79994

**Comment by sivaramaaa** [comment]
Hey thanks for sharing !!
