### ISSUE TITLE
house_of_orange...

### ISSUE THREAD

**Issue by vngkv123** [shellphish/how2heap#63]
In _IO_flush_lockp() function...

 813       if (((fp->_mode <= 0 && fp->_IO_write_ptr > fp->_IO_write_base)
 814 #if defined _LIBC || defined _GLIBCPP_USE_WCHAR_T
 815        || (_IO_vtable_offset (fp) == 0
 816            && fp->_mode > 0 && (fp->_wide_data->_IO_write_ptr
 817                     > fp->_wide_data->_IO_write_base))
 818 #endif
 819        )
 820       && _IO_OVERFLOW (fp, EOF) == EOF)

we just satisfy (fp->_mode <= 0 && fp-> _IO_write_ptr > fp->_IO_write_base)

or (_IO_vtable_offset(fp) == 0 && fp->_mode > 0 && (fp->_wide_data->_IO_write_ptr > fp->_wide_data -> _IO_write_base)

I think former is more eaiser than later.

**Comment by m1ghtym0** [comment]
Thanks for noticing:-)
Hope that makes it even more clear

**Comment by m1ghtym0** [comment]
@zardus I guess you can close this

**Comment by zardus** [comment]
Bumo.
