### ISSUE TITLE
blind chunk unmaping

### ISSUE THREAD

**Issue by Eterna1** [shellphish/how2heap#67]
I enjoyed this method because it differs from others.
It is implemented here: https://github.com/andigena/ptmalloc-fanzine/blob/master/01-madness/blind_chunk_unmapping.c
and here is an article about this: http://tukan.farm/2016/07/27/munmap-madness/

We have 2 mapped chunks A and B. After overwriting heap metada, freeing chunk A makes chunk B freed. This method can be used as preparations to further attack like UAF.

**Comment by Kyle-Kyle** [comment]
I think the technique has been implemented some time ago. It's called `mmap_overlapping_chunks.c` in this project. Not sure why no one closes this issue.
I'll close this now. But if you think `blind_chunk_unmapping` is different from `mmap_overlapping_chunks`, feel free to reopen it.
Thanks!
