### ISSUE TITLE
unsafe_unlink doesn't work with glibc 2.26

### ISSUE THREAD

**Issue by firmianay** [shellphish/how2heap#68]
hi, I got a problem when running unsafe_unlink on my Linux which has glibc 2.26. 
You have tested on Ubuntu16.04 which has glibc 2.23, and the following check has not been added in this version.
```
 /* Take a chunk off a bin list */
 #define unlink(AV, P, BK, FD) {                                            \
+    if (__builtin_expect (chunksize(P) != prev_size (next_chunk(P)), 0))      \
+      malloc_printerr (check_action, "corrupted size vs. prev_size", P, AV);  \
     FD = P->fd;                                                                      \
     BK = P->bk;                                                                      \
     if (__builtin_expect (FD->bk != P || BK->fd != P, 0))                    \
```
In unsafe_unlink.c, These comments indicate that the check should be bypassed
```
We need to make sure the 'size' of our fake chunk matches the 'previous_size' of the next chunk (chunk+size)
With this setup we can pass this check: (chunksize(P) != prev_size (next_chunk(P)) == False
P = chunk0_ptr, next_chunk(P) == (mchunkptr) (((char *) (p)) + chunksize (p)) == chunk0_ptr + (chunk0_ptr[1]&(~ 0x7))
If x = chunk0_ptr[1] & (~ 0x7), that is x = *(chunk0_ptr + x).
We just need to set the *(chunk0_ptr + x) = x, so we can pass the check
1.Now the x = chunk0_ptr[1]&(~0x7) = 0, we should set the *(chunk0_ptr + 0) = 0, in other words we should do nothing
2.Further more we set chunk0_ptr = 0x8 in 64-bits environment, then *(chunk0_ptr + 0x8) == chunk0_ptr[1], it's fine to pass
3.Finally we can also set chunk0_ptr[1] = x in 64-bits env, and set *(chunk0_ptr+x)=x,for example chunk_ptr0[1] = 0x20, chunk_ptr0[4] = 0x20
In this case we set the 'size' of our fake chunk so that chunk0_ptr + size (0x555555757268) == chunk0_ptr->size (0x555555757268)
You can find the commitdiff of this check at https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=17f487b7afa7cd6c316040f3e6c86dc96b2eec30
```
But not, I don't know why. Could you explain it for me?
```
Original value: Hello!~
New Value: Hello!~
```

**Comment by P4N74** [comment]
This happens because of tcache. As explained in this [blog](http://tukan.farm/2017/07/08/tcache/):
```
Some observations:
1. the tcache fill code in the fast path of malloc will reverse the order of the chunks.
2. cached chunks won’t be coalesced
    2.1 neither on free of neighboring chunks
    2.2 nor with top when they are freed
```
Since there won't be any coalescing of chunks while freeing `chunk1_ptr`, `chunk0_ptr` will still be pointing to correct heap location rather than `&chunk0_ptr - 0x18`.

One possible way to fix this is to fill up the tcache for that specific chunk size, so that upon next free of that chunk size would go into bins (as expected) and thus result into coalescing with previous chunk.

Adding the following line works, but I am not sure if that would be helpful other than this specific environment.
```
	for (i = 0; i < 7; i++) {
		a[i] = malloc(0x80);
	}
	for (i = 0; i < 7; i++) {
		free(a[i]);
	}
	free(chunk1_ptr);
```

**Comment by m1ghtym0** [comment]
@P4N74 is correct. I'm not sure about the fix though, tcache will most likely affect other attacks as well,
a quick test gave me: unsafe_unlink, house_of_lore, overlapping_chunks, poison_null_byte
We should probably think about presenting new mitigations added to the libc in a better way in this repo.

**Comment by firmianay** [comment]
@P4N74 @m1ghtym0 Amazing, thank you!
