### ISSUE TITLE
Add House of Roman

### ISSUE THREAD

**Issue by infernalheaven** [shellphish/how2heap#76]
Suggest adding House of Roman, which is a combination of existing heap techniques that do not require a leak.

- https://gist.github.com/romanking98/9aab2804832c0fb46615f025e8ffb0bc
- https://github.com/romanking98/House-Of-Roman

**Comment by n30m1nd** [comment]
Nice technique!

Could do with a better explanation as it might not be clear for some people that `__malloc_hook` is always just a few bytes behind `&main_arena->top`.

**Comment by mdulin2** [comment]
The House of Roman was added recently. This issue should be closed.
