### ISSUE TITLE
glibc 2.25 poison_null_byte

### ISSUE THREAD

**Issue by beswing** [shellphish/how2heap#87]
in glibc.2.23 and glibc 2.24 have the check ：chunk_size == next->prev->chunk_size 

so the poison_null_byte done'st work. like this:
![image](https://user-images.githubusercontent.com/30622351/44140892-14f01714-a0ae-11e8-88cf-f15fce006884.png)

so we should bypass the check ,like glibc 2.6  poison_null_byte.c

**Comment by m1ghtym0** [comment]
This is absolutely correct, the check was merged in 2.23.
Thanks for noticing!
