### ISSUE TITLE
Typo on house of spirit... I think

### ISSUE THREAD

**Issue by pentallelogram** [shellphish/how2heap#91]
https://github.com/shellphish/how2heap/blob/81ab9204161055517992997a6b606f9b428e3251/glibc_2.25/house_of_spirit.c#L16

On this line I believe `&fake_chunks[7]` should be `&fake_chunks[9]` given that the next header is placed like so: `fake_chunks[9] = 0x1234; // nextsize`

**Comment by pentallelogram** [comment]
while I'm at it with the typo's this line: https://github.com/shellphish/how2heap/blob/81ab9204161055517992997a6b606f9b428e3251/glibc_2.26/tcache_poisoning.c#L29

`2st`

**Comment by m1ghtym0** [comment]
Thanks!
