### ISSUE TITLE
Reorganize

### ISSUE THREAD

**Issue by m1ghtym0** [shellphish/how2heap#97]
The current folders `glibc_2.25` and `glibc_2.26` don't really make sense anymore.
I would prefer something like `deprecated` and `active`.
However, we often have multiple stages of deprecated, which are working around several checks until finally killed...
Maybe we should create a folder for each major technique in `deprecated` and keep several versions in there, thoughts?

**Comment by zardus** [comment]
I'm fine with that, but wouldn't we just end up with `deprecated/tcache_dup_2.27.c` and so forth anyways? Is it different than the current method?

**Comment by m1ghtym0** [comment]
It would probably look like that, yes.
If I would see this repo the first time right now, I would expect for the files in 2.26 to be strongly connected to this version. However, now this folder contains all the attacks for versions >= 2.26, so some of them are only mildly connect to 2.26.
Maybe it's just me and this not really an issue, so we should just keep it the way it is;-)

**Comment by Kyle-Kyle** [comment]
I think we should reorganize now.
There are more and more techniques working in 2.27 but not in 2.31.
For some of them, people managed to create new pocs to bypass new defenses while at the same time having the same power as the old ones. And currently, the old pocs and new pocs are all placed in 2.26 folder which comes super confusing now.
My quick idea is to separate them by versions. And we don't need to finish all versions at once. We can separate them roughly like 2.23, 2.27, 2.31 first(ubuntu LTS releases). And if we have time later, we make finer separations.

**Comment by Kyle-Kyle** [comment]
The reorganization is done now. Let me close this. But feel free to reopen it if you have ideas to better organize it
